### PR TITLE
Fixed json primitive parsing

### PR DESCRIPTION
**Pull request by VovaStelmashchuk**
I found a bad, SDK return a JsonLiteral instead of primitive types. 
1. Added convert json element into kotlin types
2. Added test for check the case.

### CODE REVIEW

**Comment by VovaStelmashchuk** [comment]
Merge after #11, the PR has fixs for pipeline.

**Comment by jdorn** [comment]
I merged #11, is this good to go now?

**Comment by VovaStelmashchuk** [comment]
Yep, need just merge main into my branch. Give me a few minutes.

**Comment by VovaStelmashchuk** [comment]
@jdorn  Ready to merge

**Pull request merged**
